<script lang="ts">
	import ProjectImage from '$lib/projectimage.svelte';
	import Tiltcard from '$lib/tiltcard.svelte';
	import Flipin from '$lib/effects/flipin.svelte';

	const projects: WorkProject[] = [
		{
			name: 'LLAMA CHAT',
			img: '/images/llamachat.webp',
			skills: ['NextJS', 'Websockets', 'tailwindCSS', 'Typescript'],
			description: 'A chat app built on top of websocket technology',
			github: 'https://github.com/JPTomorrow/nextjs-pusher-railway-chat-app',
			site: 'https://justins-chat-app.up.railway.app/'
		},
		{
			name: 'BOM Generator',
			img: '/images/bom-generator.webp',
			skills: ['C#', 'WPF'],
			description:
				'Uses Revit API for interoperability with Autodesk Revit. Generates Bill of Materials from the 3D CAD models that Revit produces',
			github: 'https://github.com/JPTomorrow/revit-bill-of-materials-generator',
			site: ''
		},
		{
			name: 'Game of Life',
			img: '/images/gol.webp',
			skills: ['React', 'NextJS', 'three.js', 'WebGL'],
			description: "A classic implementation of Conway's Game of Life with three.js",
			github: 'https://github.com/JPTomorrow/nextjs-gol',
			site: 'https://nextjs-game-of-life-production.up.railway.app/'
		},
		{
			name: 'Marathon Training Videos',
			img: '/images/marathon-training-videos-pic.webp',
			skills: ['Vue', 'Microsoft Azure', "API's"],
			description: 'A website for training marathon field workers in construction safety',
			github: 'https://github.com/JPTomorrow/marathon-training-videos'
		},
		{
			name: 'SecPad',
			img: '/images/secpad.webp',
			skills: ['React', 'NextJS', 'Local Storage'],
			description: 'A note taking app that uses local storage to store the notes',
			github: 'https://github.com/JPTomorrow/secpad',
			site: 'https://todo-app-production-6463.up.railway.app/'
		},
		{
			name: 'Bluebeam BOM Generator',
			img: '/images/bluebeam-in-wall-fire-alarm.webp',
			skills: ['C#', '.NET Core', 'PDF format parsing'],
			description:
				"Generates a Bill of Materials for In Wall devices and Fire Alarm Systems using PDF's generated by Bluebeam",
			github: 'https://github.com/JPTomorrow/bluebeam-pthree-in-wall'
		}
	];
</script>

<div
	class="transparent-gradient-fade w-7/8 snap-x scroll-px-5 snap-mandatory scroll-smooth flex gap-4 overflow-x-auto px-4 py-10"
>
	{#each projects as currentProject, i (i)}
		<Tiltcard size="w-snap-start shrink-0 w-80">
			<Flipin delay={i * 0.1}>
				<div
					class="flex h-full flex-col border-[2px] border-t-[3px] border-secondary-300 rounded-xl transition-transform hover:scale-105 duration-75 shadow-xl"
				>
					<ProjectImage src={currentProject.img} />
					<div
						class="transparent-gradient-fade absolute-centered bg-black bg-opacity-50 w-full h-fit py-5 border-[2px] border-secondary-600"
					>
						<h1 class="text-2xl font-semibold px-5">{currentProject.name}</h1>
					</div>
					<!-- <div class="flex flex-col w-full h-full text-left p-5">
							<h2>{currentProject.description}</h2>
							<div class="flex flex-grow items-end flex-wrap gap-3 mt-3">
								{#each currentProject.skills as s, i (i)}
									<span class="badge variant-filled rounded-full">{s}</span>
								{/each}
							</div>
						</div> -->
				</div>
			</Flipin>
		</Tiltcard>
	{/each}
</div>

<style>
	.transparent-gradient-fade {
		--mask: linear-gradient(
				to right,
				rgba(0, 0, 0, 0) 0,
				rgba(0, 0, 0, 1) 10%,
				rgba(0, 0, 0, 1) 90%,
				rgba(0, 0, 0, 0) 100%
			)
			100% 50% / 100% 100% repeat-x;

		font: 2em/1.6em Arial;
		-webkit-mask: var(--mask);
		mask: var(--mask);
	}
</style>
