<script lang="ts">
	import Tiltcard from '$lib/tiltcard.svelte';
	import Flipin from '$lib/effects/flipin.svelte';
	import { setShowModal } from '$lib/modalStore';

	const projects: WorkProject[] = [
		{
			name: 'LLAMA CHAT',
			img: '/images/llamachat.webp',
			skills: ['NextJS', 'Websockets', 'tailwindCSS', 'Typescript'],
			description: 'A chat app built on top of websocket technology',
			github: 'https://github.com/JPTomorrow/nextjs-pusher-railway-chat-app',
			site: 'https://justins-chat-app.up.railway.app/'
		},
		{
			name: 'BOM Generator',
			img: '/images/bom-generator.webp',
			skills: ['C#', 'WPF'],
			description:
				'Uses Revit API for interoperability with Autodesk Revit. Generates Bill of Materials from the 3D CAD models that Revit produces',
			github: 'https://github.com/JPTomorrow/revit-bill-of-materials-generator',
			site: ''
		},
		{
			name: 'Game of Life',
			img: '/images/gol.webp',
			skills: ['React', 'NextJS', 'three.js', 'WebGL'],
			description: "A classic implementation of Conway's Game of Life with three.js",
			github: 'https://github.com/JPTomorrow/nextjs-gol',
			site: 'https://nextjs-game-of-life-production.up.railway.app/'
		},
		{
			name: 'Marathon Training Videos',
			img: '/images/marathon-training-videos-pic.webp',
			skills: ['Vue', 'Microsoft Azure', "API's"],
			description: 'A website for training marathon field workers in construction safety',
			github: 'https://github.com/JPTomorrow/marathon-training-videos'
		},
		{
			name: 'SecPad',
			img: '/images/secpad.webp',
			skills: ['React', 'NextJS', 'Local Storage'],
			description: 'A note taking app that uses local storage to store the notes',
			github: 'https://github.com/JPTomorrow/secpad',
			site: 'https://todo-app-production-6463.up.railway.app/'
		},
		{
			name: 'Bluebeam BOM Generator',
			img: '/images/bluebeam-in-wall-fire-alarm.webp',
			skills: ['C#', '.NET Core', 'PDF format parsing'],
			description:
				"Generates a Bill of Materials for In Wall devices and Fire Alarm Systems using PDF's generated by Bluebeam",
			github: 'https://github.com/JPTomorrow/bluebeam-pthree-in-wall'
		}
	];

	const work = [...'WORK'];
</script>

<div class="flex w-7/8 justify-between border-y-[1px] border-secondary-500 px-80 py-3 mt-5">
	{#each work as c, i (i)}
		<p class="text-7xl font-thin">{c}</p>
	{/each}
</div>

<div
	class="transparent-gradient-fade w-7/8 snap-x scroll-px-5 snap-mandatory scroll-smooth flex gap-8 overflow-x-auto px-10 py-10"
>
	{#each projects as currentProject, i (i)}
		<Tiltcard size="snap-center shrink-0 h-80 aspect-video">
			<Flipin delay={i * 0.1}>
				<button
					class="flex w-full h-full flex-col border-y-[3px] border-secondary-500 border-double rounded-xl transition-transform hover:scale-105 duration-75 shadow-xl"
					on:click={() => {
						setShowModal(currentProject);
					}}
				>
					<img alt="pimg" class="w-full h-full rounded-xl object-cover" src={currentProject.img} />
					<div
						class="transparent-gradient-fade absolute-centered bg-black bg-opacity-80 w-full h-fit py-5 border-y-[2px] border-secondary-600"
					>
						<p class="text-3xl font-thin px-5">{currentProject.name}</p>
					</div>
				</button>
			</Flipin>
		</Tiltcard>
	{/each}
</div>

<style lang="postcss">
	.transparent-gradient-fade {
		--mask: linear-gradient(
				to right,
				rgba(0, 0, 0, 0.5) 0,
				rgba(0, 0, 0, 1) 5%,
				rgba(0, 0, 0, 1) 95%,
				rgba(0, 0, 0, 0.5) 100%
			)
			100% 50% / 100% 100% repeat-x;

		-webkit-mask: var(--mask);
		mask: var(--mask);
	}
</style>
