<script lang="ts">
	import ProjectImage from '$lib/projectimage.svelte';

	import { fade } from 'svelte/transition';
	import { setScrollY } from '$lib/scrollstore';
	import { onMount } from 'svelte';
	import Tiltcard from '$lib/tiltcard.svelte';
	import Flipin from '$lib/effects/flipin.svelte';
	import Github from '$lib/github.svelte';

	const projects: WorkProject[] = [
		{
			name: 'LLAMA CHAT',
			img: '/images/llamachat.webp',
			skills: ['NextJS', 'Websockets', 'tailwindCSS', 'Typescript'],
			description: 'A chat app built on top of websocket technology',
			github: 'https://github.com/JPTomorrow/nextjs-pusher-railway-chat-app',
			site: 'https://justins-chat-app.up.railway.app/'
		},
		{
			name: 'BOM Generator',
			img: '/images/bom-generator.webp',
			skills: ['C#', 'WPF'],
			description:
				'Uses Revit API for interoperability with Autodesk Revit. Generates Bill of Materials from the 3D CAD models that Revit produces',
			github: 'https://github.com/JPTomorrow/revit-bill-of-materials-generator',
			site: ''
		},
		{
			name: 'Game of Life',
			img: '/images/gol.webp',
			skills: ['React', 'NextJS', 'three.js', 'WebGL'],
			description: "A classic implementation of Conway's Game of Life with three.js",
			github: 'https://github.com/JPTomorrow/nextjs-gol',
			site: 'https://nextjs-game-of-life-production.up.railway.app/'
		},
		{
			name: 'Marathon Training Videos',
			img: '/images/marathon-training-videos-pic.webp',
			skills: ['Vue', 'Microsoft Azure', "API's"],
			description: 'A website for training marathon field workers in construction safety',
			github: 'https://github.com/JPTomorrow/marathon-training-videos'
		},
		{
			name: 'SecPad',
			img: '/images/secpad.webp',
			skills: ['React', 'NextJS', 'Local Storage'],
			description: 'A note taking app that uses local storage to store the notes',
			github: 'https://github.com/JPTomorrow/secpad',
			site: 'https://todo-app-production-6463.up.railway.app/'
		},
		{
			name: 'Bluebeam BOM Generator',
			img: '/images/bluebeam-in-wall-fire-alarm.webp',
			skills: ['C#', '.NET Core', 'PDF format parsing'],
			description:
				"Generates a Bill of Materials for In Wall devices and Fire Alarm Systems using PDF's generated by Bluebeam",
			github: 'https://github.com/JPTomorrow/bluebeam-pthree-in-wall'
		}
	];

	let outer: HTMLDivElement;
	onMount(() => {
		outer.addEventListener('scroll', (e) => {
			setScrollY(outer.scrollTop);
		});
	});
</script>

<div
	bind:this={outer}
	in:fade|global={{ duration: 200 }}
	class="grid grid-cols-2 md:grid-cols-3 gap-10 w-screen h-screen px-[30px] md:px-[80px] py-[100px] overflow-y-scroll"
>
	{#each projects as currentProject, i (i)}
		<Tiltcard size="w-full h-full">
			<Flipin delay={i * 0.1}>
				<div
					class="flex h-full flex-col border-[2px] border-t-[10px] border-primary-300 rounded-xl"
				>
					<ProjectImage src={currentProject.img} />
					<div class="flex flex-col w-full h-full text-left p-5">
						<h1 class="text-2xl">{currentProject.name}</h1>
						<h2>{currentProject.description}</h2>
						<div class="flex flex-grow items-end flex-wrap gap-3 mt-3">
							{#each currentProject.skills as s, i (i)}
								<span class="badge variant-filled rounded-full">{s}</span>
							{/each}
						</div>
					</div>
				</div>
			</Flipin>
		</Tiltcard>
	{/each}
</div>
